project:
  type: book

book:
  title: "Improving your statistical inferences through Monte Carlo simulations"
  subtitle: "in R and tidyverse"
  author: "Ian Hussey"
  date: today
  chapters:
    - index.qmd
    # Concepts and coding skills
    - chapters/foundational_concepts.qmd
    - chapters/writing_functions.qmd
    #- chapters/generating_data.qmd
    #- chapters/analysing_data.qmd
    - chapters/designing_simulation_experiments.qmd
    - chapters/mapping_functions.qmd
    #- chapters/general_structure_of_a_simulation_1.qmd # removed to /old folder
    #- chapters/general_structure_of_a_simulation_2.qmd # removed to /old folder
    
    # Applications and more advanced coding skills
    - chapters/violating_assumptions.qmd
    - chapters/testing_assumptions_and_conditional_tests.qmd
    - chapters/p_hacking.qmd
    - chapters/p_values_and_confidence_intervals.qmd
    - chapters/difference_between_signfiicant_and_nonsignificant.qmd
    - chapters/standardized_effect_sizes_and_range_restriction.qmd
    - chapters/impact_of_lazy_responding_assignment.qmd
    - chapters/meta_analysis_and_publication_bias.qmd
    - chapters/causality.qmd
    - chapters/license.qmd

# bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    code-tools: true
    warning: false
    theme: cosmo
    #embed-resources: false
    #highlight: haddock

editor: visual

cover-image: cover.png

